config/routes.rb
Rails.application.routes.draw do
  resources :deposits
  resources :receipts
  resources :discount_types
  resources :payment_types
  get '/clients/get_client'

  resources :invoices
  resources :taxes
  resources :employees
  resources :dashboards, only: [:index]
  resources :vendors
  resources :clients
  resources :products
  resources :sub_categories
  resources :categories

  root to: "dashboards#index"

  resources :products do
    collection { post :import }
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product_categories
	has_many :products, through: :product_categories

	has_many :category_sub_category
	has_many :sub_categories, through: :category_sub_category

	validates :name, presence: true
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :invoices
	has_many :receipts
end

app/models/deposit.rb
class Deposit < ApplicationRecord
	has_many :receipts
end

app/models/discount_type.rb
class DiscountType < ApplicationRecord
	has_many :invoices
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	mount_uploader :attachment, InvoiceAttachmentUploader

	has_many :invoice_products
	has_many :products, through: :invoice_products
	has_many :receipts

	belongs_to :client
	belongs_to :tax
	belongs_to :discount_type
end

app/models/invoice_product.rb
class InvoiceProduct < ApplicationRecord
	belongs_to :invoice
	belongs_to :product
end

app/models/payment_type.rb
class PaymentType < ApplicationRecord
	has_many :receipts
	
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ProductImageUploader 

	has_many :product_categories
	has_many :categories, through: :product_categories

	has_many :product_vendors
	has_many :vendors, through: :product_vendors

  has_many :invoice_products
  has_many :invoices, through: :invoice_products

	def self.to_csv(options = {}) 
    CSV.generate(options) do |csv| 
      csv << column_names 
      all.each do |product| 
        csv << product.attributes.values_at(*column_names) 
      end 
    end 
  end 
end

app/models/product_vendor.rb
class ProductVendor < ApplicationRecord
	belongs_to :product 
	belongs_to :vendor
end

app/models/receipt.rb
class Receipt < ApplicationRecord
	belongs_to :invoice
	belongs_to :payment_type
	belongs_to :deposit
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
	has_many :category_sub_category
	has_many :categories, through: :category_sub_category

	validates :name, presence: true
end

app/models/tax.rb
class Tax < ApplicationRecord
end

app/models/vendor.rb
class Vendor < ApplicationRecord
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    @sub_categories = SubCategory.all
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
  end

  # GET /sub_categories/1/edit
  def edit
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully created.' }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: 'Sub category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_category_params
      params.require(:sub_category).permit(:name)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/sub_categories/_form.html.erb
<%= form_for(sub_category) do |f| %>
  <% if sub_category.errors.any? %>
    <div class="alert">
      <div class="row">
        <div class="col s12">
          <div class="card-panel red">
            <span class="white-text">         
              <div id="error_explanation">
                <h6><%= pluralize(sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h6>

                <ul>
                <% sub_category.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_categories/edit.html.erb
<h1>Editing Sub Category</h1>

<%= render 'form', sub_category: @sub_category %>

<%= link_to 'Show', @sub_category %> |
<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/index.html.erb
<% if alert %>
  <div class="alert">
    <div class="row">
      <div class="col s12">
        <div class="card-panel red">
          <span class="white-text">         
            <div id="error_explanation">
               <p id="alert"><%= alert %></p>
            </div>
          </span>
        </div>
      </div>
    </div>
  </div> 
<% end %>

<% if notice %>
  <div class="alert">
    <div class="row">
      <div class="col s12">
        <div class="card-panel green">
          <span class="white-text">         
            <div id="error_explanation">
               <p id="notice"><%= notice %></p>
            </div>
          </span>
        </div>
      </div>
    </div>
  </div> 
<% end %>

<h1>Sub Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= sub_category.name %></td>
        <td><%= link_to 'Show', sub_category %></td>
        <td><%= link_to 'Edit', edit_sub_category_path(sub_category) %></td>
        <td><%= link_to 'Destroy', sub_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub Category', new_sub_category_path %>

app/views/sub_categories/new.html.erb
<h1>New Sub Category</h1>

<%= render 'form', sub_category: @sub_category %>

<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/show.html.erb
<% if alert %>
  <div class="alert">
    <div class="row">
      <div class="col s12">
        <div class="card-panel red">
          <span class="white-text">         
            <div id="error_explanation">
               <p id="alert"><%= alert %></p>
            </div>
          </span>
        </div>
      </div>
    </div>
  </div> 
<% end %>

<% if notice %>
  <div class="alert">
    <div class="row">
      <div class="col s12">
        <div class="card-panel green">
          <span class="white-text">         
            <div id="error_explanation">
               <p id="notice"><%= notice %></p>
            </div>
          </span>
        </div>
      </div>
    </div>
  </div> 
<% end %>

<p>
  <strong>Name:</strong>
  <%= @sub_category.name %>
</p>

<%= link_to 'Edit', edit_sub_category_path(@sub_category) %> |
<%= link_to 'Back', sub_categories_path %>