config/routes.rb
Rails.application.routes.draw do
  resources :deposits
  resources :receipts
  resources :discount_types
  resources :payment_types
  get '/clients/get_client'

  resources :invoices
  resources :taxes
  resources :employees
  resources :dashboards, only: [:index]
  resources :vendors
  resources :clients
  resources :products
  resources :sub_categories
  resources :categories

  root to: "dashboards#index"

  resources :products do
    collection { post :import }
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product_categories
	has_many :products, through: :product_categories

	has_many :category_sub_category
	has_many :sub_categories, through: :category_sub_category

	validates :name, presence: true
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :invoices
	has_many :receipts
end

app/models/deposit.rb
class Deposit < ApplicationRecord
	has_many :receipts
end

app/models/discount_type.rb
class DiscountType < ApplicationRecord
	has_many :invoices
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	mount_uploader :attachment, InvoiceAttachmentUploader

	has_many :invoice_products
	has_many :products, through: :invoice_products
	has_many :receipts

	belongs_to :client
	belongs_to :tax
	belongs_to :discount_type
end

app/models/invoice_product.rb
class InvoiceProduct < ApplicationRecord
	belongs_to :invoice
	belongs_to :product
end

app/models/payment_type.rb
class PaymentType < ApplicationRecord
	has_many :receipts
	
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ProductImageUploader 

	has_many :product_categories
	has_many :categories, through: :product_categories

	has_many :product_vendors
	has_many :vendors, through: :product_vendors

  has_many :invoice_products
  has_many :invoices, through: :invoice_products

	def self.to_csv(options = {}) 
    CSV.generate(options) do |csv| 
      csv << column_names 
      all.each do |product| 
        csv << product.attributes.values_at(*column_names) 
      end 
    end 
  end 
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
	belongs_to :product 
	belongs_to :category
end

app/models/product_vendor.rb
class ProductVendor < ApplicationRecord
	belongs_to :product 
	belongs_to :vendor
end

app/models/receipt.rb
class Receipt < ApplicationRecord
	belongs_to :invoice
	belongs_to :payment_type
	belongs_to :deposit
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
	has_many :category_sub_category
	has_many :categories, through: :category_sub_category

	validates :name, presence: true
end

app/models/tax.rb
class Tax < ApplicationRecord
end

app/models/vendor.rb
class Vendor < ApplicationRecord
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  before_action :set_deposit, only: [:show, :edit, :update, :destroy]

  # GET /deposits
  # GET /deposits.json
  def index
    @deposits = Deposit.all
  end

  # GET /deposits/1
  # GET /deposits/1.json
  def show
  end

  # GET /deposits/new
  def new
    @deposit = Deposit.new
  end

  # GET /deposits/1/edit
  def edit
  end

  # POST /deposits
  # POST /deposits.json
  def create
    @deposit = Deposit.new(deposit_params)

    respond_to do |format|
      if @deposit.save
        format.html { redirect_to @deposit, notice: 'Deposit was successfully created.' }
        format.json { render :show, status: :created, location: @deposit }
      else
        format.html { render :new }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deposits/1
  # PATCH/PUT /deposits/1.json
  def update
    respond_to do |format|
      if @deposit.update(deposit_params)
        format.html { redirect_to @deposit, notice: 'Deposit was successfully updated.' }
        format.json { render :show, status: :ok, location: @deposit }
      else
        format.html { render :edit }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deposits/1
  # DELETE /deposits/1.json
  def destroy
    @deposit.destroy
    respond_to do |format|
      format.html { redirect_to deposits_url, notice: 'Deposit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deposit
      @deposit = Deposit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deposit_params
      params.require(:deposit).permit(:name)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/deposits/_form.html.erb
<%= form_for(deposit) do |f| %>
  <% if deposit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deposit.errors.count, "error") %> prohibited this deposit from being saved:</h2>

      <ul>
      <% deposit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deposits/edit.html.erb
<h1>Editing Deposit</h1>

<%= render 'form', deposit: @deposit %>

<%= link_to 'Show', @deposit %> |
<%= link_to 'Back', deposits_path %>

app/views/deposits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deposits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deposits.each do |deposit| %>
      <tr>
        <td><%= deposit.name %></td>
        <td><%= link_to 'Show', deposit %></td>
        <td><%= link_to 'Edit', edit_deposit_path(deposit) %></td>
        <td><%= link_to 'Destroy', deposit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deposit', new_deposit_path %>

app/views/deposits/new.html.erb
<h1>New Deposit</h1>

<%= render 'form', deposit: @deposit %>

<%= link_to 'Back', deposits_path %>

app/views/deposits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @deposit.name %>
</p>

<%= link_to 'Edit', edit_deposit_path(@deposit) %> |
<%= link_to 'Back', deposits_path %>