config/routes.rb
Rails.application.routes.draw do
  resources :deposits
  resources :receipts
  resources :discount_types
  resources :payment_types
  get '/clients/get_client'

  resources :invoices
  resources :taxes
  resources :employees
  resources :dashboards, only: [:index]
  resources :vendors
  resources :clients
  resources :products
  resources :sub_categories
  resources :categories

  root to: "dashboards#index"

  resources :products do
    collection { post :import }
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product_categories
	has_many :products, through: :product_categories

	has_many :category_sub_category
	has_many :sub_categories, through: :category_sub_category

	validates :name, presence: true
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :invoices
	has_many :receipts
end

app/models/deposit.rb
class Deposit < ApplicationRecord
	has_many :receipts
end

app/models/discount_type.rb
class DiscountType < ApplicationRecord
	has_many :invoices
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	mount_uploader :attachment, InvoiceAttachmentUploader

	has_many :invoice_products
	has_many :products, through: :invoice_products
	has_many :receipts

	belongs_to :client
	belongs_to :tax
	belongs_to :discount_type
end

app/models/invoice_product.rb
class InvoiceProduct < ApplicationRecord
	belongs_to :invoice
	belongs_to :product
end

app/models/payment_type.rb
class PaymentType < ApplicationRecord
	has_many :receipts
	
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ProductImageUploader 

	has_many :product_categories
	has_many :categories, through: :product_categories

	has_many :product_vendors
	has_many :vendors, through: :product_vendors

  has_many :invoice_products
  has_many :invoices, through: :invoice_products

	def self.to_csv(options = {}) 
    CSV.generate(options) do |csv| 
      csv << column_names 
      all.each do |product| 
        csv << product.attributes.values_at(*column_names) 
      end 
    end 
  end 
end

app/models/product_vendor.rb
class ProductVendor < ApplicationRecord
	belongs_to :product 
	belongs_to :vendor
end

app/models/receipt.rb
class Receipt < ApplicationRecord
	belongs_to :invoice
	belongs_to :payment_type
	belongs_to :deposit
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
	has_many :category_sub_category
	has_many :categories, through: :category_sub_category

	validates :name, presence: true
end

app/models/tax.rb
class Tax < ApplicationRecord
end

app/models/vendor.rb
class Vendor < ApplicationRecord
end

app/controllers/discount_types_controller.rb
class DiscountTypesController < ApplicationController
  before_action :set_discount_type, only: [:show, :edit, :update, :destroy]

  # GET /discount_types
  # GET /discount_types.json
  def index
    @discount_types = DiscountType.all
  end

  # GET /discount_types/1
  # GET /discount_types/1.json
  def show
  end

  # GET /discount_types/new
  def new
    @discount_type = DiscountType.new
  end

  # GET /discount_types/1/edit
  def edit
  end

  # POST /discount_types
  # POST /discount_types.json
  def create
    @discount_type = DiscountType.new(discount_type_params)

    respond_to do |format|
      if @discount_type.save
        format.html { redirect_to @discount_type, notice: 'Discount type was successfully created.' }
        format.json { render :show, status: :created, location: @discount_type }
      else
        format.html { render :new }
        format.json { render json: @discount_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discount_types/1
  # PATCH/PUT /discount_types/1.json
  def update
    respond_to do |format|
      if @discount_type.update(discount_type_params)
        format.html { redirect_to @discount_type, notice: 'Discount type was successfully updated.' }
        format.json { render :show, status: :ok, location: @discount_type }
      else
        format.html { render :edit }
        format.json { render json: @discount_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discount_types/1
  # DELETE /discount_types/1.json
  def destroy
    @discount_type.destroy
    respond_to do |format|
      format.html { redirect_to discount_types_url, notice: 'Discount type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discount_type
      @discount_type = DiscountType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discount_type_params
      params.require(:discount_type).permit(:name, :percentage, :amount)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/discount_types_helper.rb
module DiscountTypesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/discount_types/_form.html.erb
<%= form_for(discount_type) do |f| %>
  <% if discount_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discount_type.errors.count, "error") %> prohibited this discount_type from being saved:</h2>

      <ul>
      <% discount_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :percentage %>
    <%= f.text_field :percentage %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discount_types/edit.html.erb
<h1>Editing Discount Type</h1>

<%= render 'form', discount_type: @discount_type %>

<%= link_to 'Show', @discount_type %> |
<%= link_to 'Back', discount_types_path %>

app/views/discount_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Discount Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Percentage</th>
      <th>Amount</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @discount_types.each do |discount_type| %>
      <tr>
        <td><%= discount_type.name %></td>
        <td><%= discount_type.percentage %></td>
        <td><%= discount_type.amount %></td>
        <td><%= link_to 'Show', discount_type %></td>
        <td><%= link_to 'Edit', edit_discount_type_path(discount_type) %></td>
        <td><%= link_to 'Destroy', discount_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discount Type', new_discount_type_path %>

app/views/discount_types/new.html.erb
<h1>New Discount Type</h1>

<%= render 'form', discount_type: @discount_type %>

<%= link_to 'Back', discount_types_path %>

app/views/discount_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @discount_type.name %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @discount_type.percentage %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @discount_type.amount %>
</p>

<%= link_to 'Edit', edit_discount_type_path(@discount_type) %> |
<%= link_to 'Back', discount_types_path %>